table fact_feature_gain
	lineageTag: 6fa4f8d6-6988-5428-9022-e06b200e73f9

	column target
		dataType: string
		lineageTag: 991d2f2a-9a4c-50bb-a267-c9ff3be77782
		summarizeBy: none
		sourceColumn: target

	column target_label
		dataType: string
		lineageTag: bcd155f6-23e7-517c-af92-7c6c374bfb2f
		summarizeBy: none
		sourceColumn: target_label

	column feature
		dataType: string
		lineageTag: 64af7bc1-7302-564e-adbb-f486aaa788de
		summarizeBy: none
		sourceColumn: feature

	column gain
		dataType: double
		formatString: 0.000
		lineageTag: e0c0107e-27bf-5952-ae72-23151689cfbb
		summarizeBy: sum
		sourceColumn: gain

	partition fact_feature_gain = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataPath & "\data\fact_feature_gain.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"target", type text}, {"target_label", type text}, {"feature", type text}, {"gain", type number}})
				in
				    Typed
